# Generated by Django 3.1.4 on 2021-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexiWorkForce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='Paydone',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
