# Generated by Django 3.1.4 on 2021-01-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlexiWorkForce', '0002_applied_paydone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='ProjectName',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='TActivies',
            fields=[
                ('T_sno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('T_name', models.CharField(max_length=300)),
                ('T_Email', models.CharField(max_length=500)),
                ('T_Act_date', models.DateTimeField(blank=True, null=True)),
                ('T_what_done', models.CharField(max_length=300)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlexiWorkForce.employee')),
            ],
            options={
                'db_table': 'tactivies',
            },
        ),
    ]
